### ISSUE TITLE
Uses end of life runtime

### ISSUE THREAD

**Issue by Kirtai** [birros/web-archives#30] opened 2022-12-21 19:04 UTC
```
Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.birros.WebArchives
```

**Comment by birros** [comment] 2022-12-21 21:21
Duplicate of #29

**Closed as completed by birros** 2022-12-21 21:21 UTC
